# api:
#   build: ./api
#   volumes:
#     - ./api:/usr/src/app
#     - /usr/src/app/node_modules
#   environment:
#     - AWS_ACCESS_KEY_ID
#     - AWS_SECRET_ACCESS_KEY
#     - AWS_DEFAULT_REGION
#
client:
  build: ./client
  volumes:
    - ./client:/usr/src/app
    - /usr/src/app/node_modules
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
